"""api tokens

Revision ID: 4011c20ef405
Revises: cb7446dc3ec9
Create Date: 2019-09-05 17:25:54.842202

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4011c20ef405'
down_revision = 'cb7446dc3ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('access_token_expiration', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('refresh_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_access_token_expiration'), 'user', ['access_token_expiration'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_access_token_expiration'), table_name='user')
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'access_token_expiration')
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###
