"""add channel and video models

Revision ID: 5cc924465384
Revises: 4011c20ef405
Create Date: 2019-09-12 10:54:46.475602

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5cc924465384'
down_revision = '4011c20ef405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('profile_image_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_display_name'), 'channel', ['display_name'], unique=False)
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=256), nullable=True),
    sa.Column('video_type', sa.String(length=16), nullable=True),
    sa.Column('duration', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_created_at'), 'video', ['created_at'], unique=False)
    op.create_index(op.f('ix_video_video_type'), 'video', ['video_type'], unique=False)
    op.add_column('user', sa.Column('profile_image_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image_url')
    op.drop_index(op.f('ix_video_video_type'), table_name='video')
    op.drop_index(op.f('ix_video_created_at'), table_name='video')
    op.drop_table('video')
    op.drop_table('follows')
    op.drop_index(op.f('ix_channel_display_name'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
