"""initial

Revision ID: cb7446dc3ec9
Revises: 
Create Date: 2019-09-04 18:16:03.702880

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cb7446dc3ec9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_id', sa.Integer(), nullable=True),
    sa.Column('twitch_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_twitch_id'), 'user', ['twitch_id'], unique=True)
    op.create_index(op.f('ix_user_twitch_name'), 'user', ['twitch_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_twitch_name'), table_name='user')
    op.drop_index(op.f('ix_user_twitch_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
