"""add channel login name

Revision ID: e3231c65260c
Revises: 0395b3aaaea1
Create Date: 2019-09-13 13:41:34.264046

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e3231c65260c'
down_revision = '0395b3aaaea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('login_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_channel_login_name'), 'channel', ['login_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_login_name'), table_name='channel')
    op.drop_column('channel', 'login_name')
    # ### end Alembic commands ###
